#services:
#  db:
#    image: postgres
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
##    restart: always
#    environment:
#      - POSTGRES_DB=book_platform
#      - POSTGRES_USER=tynchtykbek
#      - POSTGRES_PASSWORD=tynchtyk
#  web:
#    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
#    ports:
#      - "8000:8000"
#    environment:
#      - POSTGRES_NAME=book_platform
#      - POSTGRES_USER=tynchtykbek
#      - POSTGRES_PASSWORD=tynchtyk
#    depends_on:
#      - db