# Generated by Django 4.2.1 on 2023-06-09 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='название книги')),
                ('description', models.TextField(max_length=100, verbose_name='описание книги')),
                ('author', models.CharField(max_length=50, verbose_name='автор книги')),
                ('cover', models.ImageField(upload_to='covers', verbose_name='обложка книги')),
                ('book_file', models.FileField(blank=True, upload_to='books/pdf', verbose_name=' книга в PDF формате')),
                ('book_audio', models.FileField(blank=True, upload_to='books/audio', verbose_name='книга в аудио формате')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
