# Generated by Django 4.2.1 on 2023-06-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_audio',
            field=models.FileField(blank=True, upload_to='static/book/audio', verbose_name='книга в аудио формате'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, upload_to='static/book/pdf', verbose_name=' книга в PDF формате'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to='static/book/covers', verbose_name='обложка книги'),
        ),
    ]
