# Generated by Django 4.2.1 on 2023-06-10 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_alter_book_book_audio_alter_book_book_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, upload_to='pdf', verbose_name=' книга в PDF формате'),
        ),
        migrations.CreateModel(
            name='ReadLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_later_book', to='books.book')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_later_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
