# Generated by Django 4.2.1 on 2023-06-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='read_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
